import type { Hero } from '../types';

export const HEROES: Hero[] = [
  { id: 1, name: 'Abaddon', icon: '🛡️', attr: 'str', roles: ['Offlane', 'Support'] },
  { id: 2, name: 'Alchemist', icon: '⚗️', attr: 'str', roles: ['Carry', 'Mid'] },
  { id: 3, name: 'Ancient Apparition', icon: '❄️', attr: 'int', roles: ['Support'] },
  { id: 4, name: 'Anti-Mage', icon: '⚔️', attr: 'agi', roles: ['Carry'] },
  { id: 5, name: 'Arc Warden', icon: '🌀', attr: 'agi', roles: ['Mid', 'Carry'] },
  { id: 6, name: 'Axe', icon: '🪓', attr: 'str', roles: ['Offlane'] },
  { id: 7, name: 'Bane', icon: '😈', attr: 'int', roles: ['Support'] },
  { id: 8, name: 'Batrider', icon: '🦇', attr: 'str', roles: ['Offlane', 'Mid'] },
  { id: 9, name: 'Beastmaster', icon: '🐗', attr: 'str', roles: ['Offlane'] },
  { id: 10, name: 'Bloodseeker', icon: '🩸', attr: 'agi', roles: ['Carry', 'Mid'] },
  { id: 11, name: 'Bounty Hunter', icon: '💰', attr: 'agi', roles: ['Offlane', 'Support'] },
  { id: 12, name: 'Brewmaster', icon: '🍺', attr: 'str', roles: ['Offlane'] },
  { id: 13, name: 'Bristleback', icon: '🦔', attr: 'str', roles: ['Offlane'] },
  { id: 14, name: 'Broodmother', icon: '🕷️', attr: 'str', roles: ['Offlane', 'Mid'] },
  { id: 15, name: 'Centaur Warrunner', icon: '🏇', attr: 'str', roles: ['Offlane'] },
  { id: 16, name: 'Chaos Knight', icon: '⚡', attr: 'str', roles: ['Carry'] },
  { id: 17, name: 'Chen', icon: '🙏', attr: 'int', roles: ['Support'] },
  { id: 18, name: 'Clinkz', icon: '🏹', attr: 'agi', roles: ['Carry', 'Mid'] },
  { id: 19, name: 'Clockwerk', icon: '⚙️', attr: 'str', roles: ['Offlane', 'Support'] },
  { id: 20, name: 'Crystal Maiden', icon: '❄️', attr: 'int', roles: ['Support'] },
  { id: 21, name: 'Dark Seer', icon: '🔮', attr: 'int', roles: ['Offlane'] },
  { id: 22, name: 'Dark Willow', icon: '🌿', attr: 'int', roles: ['Support'] },
  { id: 23, name: 'Dawnbreaker', icon: '☀️', attr: 'str', roles: ['Offlane', 'Support'] },
  { id: 24, name: 'Dazzle', icon: '💀', attr: 'int', roles: ['Support'] },
  { id: 25, name: 'Death Prophet', icon: '👻', attr: 'int', roles: ['Mid', 'Offlane'] },
  { id: 26, name: 'Disruptor', icon: '🌪️', attr: 'int', roles: ['Support'] },
  { id: 27, name: 'Doom', icon: '🔥', attr: 'str', roles: ['Offlane'] },
  { id: 28, name: 'Dragon Knight', icon: '🐉', attr: 'str', roles: ['Mid', 'Offlane'] },
  { id: 29, name: 'Drow Ranger', icon: '🏹', attr: 'agi', roles: ['Carry'] },
  { id: 30, name: 'Earth Spirit', icon: '🗿', attr: 'str', roles: ['Offlane', 'Support'] },
  { id: 31, name: 'Earthshaker', icon: '🌍', attr: 'str', roles: ['Offlane', 'Support'] },
  { id: 32, name: 'Elder Titan', icon: '🏛️', attr: 'str', roles: ['Offlane', 'Support'] },
  { id: 33, name: 'Ember Spirit', icon: '🔥', attr: 'agi', roles: ['Mid', 'Carry'] },
  { id: 34, name: 'Enchantress', icon: '🦌', attr: 'int', roles: ['Offlane', 'Support'] },
  { id: 35, name: 'Enigma', icon: '🕳️', attr: 'int', roles: ['Offlane', 'Support'] },
  { id: 36, name: 'Faceless Void', icon: '⏳', attr: 'agi', roles: ['Carry', 'Offlane'] },
  { id: 37, name: 'Grimstroke', icon: '🖌️', attr: 'int', roles: ['Support'] },
  { id: 38, name: 'Gyrocopter', icon: '🚁', attr: 'agi', roles: ['Carry'] },
  { id: 39, name: 'Hoodwink', icon: '🐿️', attr: 'agi', roles: ['Support', 'Offlane'] },
  { id: 40, name: 'Huskar', icon: '💉', attr: 'str', roles: ['Mid', 'Carry'] },
  { id: 41, name: 'Invoker', icon: '🔮', attr: 'int', roles: ['Mid'] },
  { id: 42, name: 'Io', icon: '⚪', attr: 'str', roles: ['Support'] },
  { id: 43, name: 'Jakiro', icon: '🐉', attr: 'int', roles: ['Support'] },
  { id: 44, name: 'Juggernaut', icon: '⚔️', attr: 'agi', roles: ['Carry'] },
  { id: 45, name: 'Keeper of the Light', icon: '💡', attr: 'int', roles: ['Support'] },
  { id: 46, name: 'Kunkka', icon: '⚓', attr: 'str', roles: ['Mid', 'Offlane'] },
  { id: 47, name: 'Legion Commander', icon: '🗡️', attr: 'str', roles: ['Offlane', 'Mid'] },
  { id: 48, name: 'Leshrac', icon: '💜', attr: 'int', roles: ['Mid', 'Support'] },
  { id: 49, name: 'Lich', icon: '🧊', attr: 'int', roles: ['Support'] },
  { id: 50, name: 'Life Stealer', icon: '👹', attr: 'str', roles: ['Carry', 'Offlane'] },
  { id: 51, name: 'Lina', icon: '🔥', attr: 'int', roles: ['Mid', 'Support'] },
  { id: 52, name: 'Lion', icon: '🦁', attr: 'int', roles: ['Support'] },
  { id: 53, name: 'Lone Druid', icon: '🐻', attr: 'str', roles: ['Mid', 'Offlane'] },
  { id: 54, name: 'Luna', icon: '🌙', attr: 'agi', roles: ['Carry'] },
  { id: 55, name: 'Lycan', icon: '🐺', attr: 'str', roles: ['Offlane', 'Carry'] },
  { id: 56, name: 'Magnus', icon: '🦏', attr: 'str', roles: ['Offlane'] },
  { id: 57, name: 'Marci', icon: '👊', attr: 'str', roles: ['Support', 'Offlane'] },
  { id: 58, name: 'Mars', icon: '🛡️', attr: 'str', roles: ['Offlane'] },
  { id: 59, name: 'Medusa', icon: '🐍', attr: 'agi', roles: ['Carry'] },
  { id: 60, name: 'Meepo', icon: '👥', attr: 'agi', roles: ['Mid', 'Carry'] },
  { id: 61, name: 'Mirana', icon: '🌙', attr: 'agi', roles: ['Carry', 'Support'] },
  { id: 62, name: 'Monkey King', icon: '🐵', attr: 'agi', roles: ['Carry', 'Mid'] },
  { id: 63, name: 'Morphling', icon: '💧', attr: 'agi', roles: ['Carry', 'Mid'] },
  { id: 64, name: 'Muerta', icon: '💀', attr: 'int', roles: ['Carry', 'Mid'] },
  { id: 65, name: 'Naga Siren', icon: '🧜', attr: 'agi', roles: ['Carry'] },
  { id: 66, name: "Nature's Prophet", icon: '🌳', attr: 'int', roles: ['Offlane', 'Mid'] },
  { id: 67, name: 'Necrophos', icon: '☠️', attr: 'int', roles: ['Mid', 'Offlane'] },
  { id: 68, name: 'Night Stalker', icon: '🌙', attr: 'str', roles: ['Offlane'] },
  { id: 69, name: 'Nyx Assassin', icon: '🦗', attr: 'agi', roles: ['Offlane', 'Support'] },
  { id: 70, name: 'Ogre Magi', icon: '👹', attr: 'str', roles: ['Support'] },
  { id: 71, name: 'Omniknight', icon: '⚜️', attr: 'str', roles: ['Offlane', 'Support'] },
  { id: 72, name: 'Oracle', icon: '🔮', attr: 'int', roles: ['Support'] },
  { id: 73, name: 'Outworld Destroyer', icon: '💎', attr: 'int', roles: ['Mid'] },
  { id: 74, name: 'Pangolier', icon: '🐉', attr: 'agi', roles: ['Mid', 'Offlane'] },
  { id: 75, name: 'Phantom Assassin', icon: '🗡️', attr: 'agi', roles: ['Carry'] },
  { id: 76, name: 'Phantom Lancer', icon: '👻', attr: 'agi', roles: ['Carry'] },
  { id: 77, name: 'Phoenix', icon: '🔥', attr: 'str', roles: ['Offlane', 'Support'] },
  { id: 78, name: 'Primal Beast', icon: '🦣', attr: 'str', roles: ['Offlane'] },
  { id: 79, name: 'Puck', icon: '🧚', attr: 'int', roles: ['Mid'] },
  { id: 80, name: 'Pudge', icon: '🪝', attr: 'str', roles: ['Offlane'] },
  { id: 81, name: 'Pugna', icon: '💀', attr: 'int', roles: ['Mid', 'Support'] },
  { id: 82, name: 'Queen of Pain', icon: '👸', attr: 'int', roles: ['Mid'] },
  { id: 83, name: 'Razor', icon: '⚡', attr: 'agi', roles: ['Carry', 'Mid'] },
  { id: 84, name: 'Riki', icon: '🗡️', attr: 'agi', roles: ['Carry', 'Offlane'] },
  { id: 85, name: 'Rubick', icon: '🪄', attr: 'int', roles: ['Support'] },
  { id: 86, name: 'Sand King', icon: '🦂', attr: 'str', roles: ['Offlane'] },
  { id: 87, name: 'Shadow Demon', icon: '👿', attr: 'int', roles: ['Support'] },
  { id: 88, name: 'Shadow Fiend', icon: '💀', attr: 'agi', roles: ['Mid'] },
  { id: 89, name: 'Shadow Shaman', icon: '🪆', attr: 'int', roles: ['Support'] },
  { id: 90, name: 'Silencer', icon: '🤫', attr: 'int', roles: ['Support', 'Mid'] },
  { id: 91, name: 'Skywrath Mage', icon: '🦅', attr: 'int', roles: ['Support', 'Mid'] },
  { id: 92, name: 'Slardar', icon: '🐟', attr: 'str', roles: ['Offlane'] },
  { id: 93, name: 'Slark', icon: '🐟', attr: 'agi', roles: ['Carry'] },
  { id: 94, name: 'Snapfire', icon: '🔥', attr: 'str', roles: ['Support', 'Offlane'] },
  { id: 95, name: 'Sniper', icon: '🎯', attr: 'agi', roles: ['Carry', 'Mid'] },
  { id: 96, name: 'Spectre', icon: '👻', attr: 'agi', roles: ['Carry'] },
  { id: 97, name: 'Spirit Breaker', icon: '🏃', attr: 'str', roles: ['Offlane', 'Support'] },
  { id: 98, name: 'Storm Spirit', icon: '⚡', attr: 'int', roles: ['Mid'] },
  { id: 99, name: 'Sven', icon: '⚔️', attr: 'str', roles: ['Carry', 'Offlane'] },
  { id: 100, name: 'Techies', icon: '💣', attr: 'int', roles: ['Support'] },
  { id: 101, name: 'Templar Assassin', icon: '🔪', attr: 'agi', roles: ['Mid', 'Carry'] },
  { id: 102, name: 'Terrorblade', icon: '😈', attr: 'agi', roles: ['Carry'] },
  { id: 103, name: 'Tidehunter', icon: '🌊', attr: 'str', roles: ['Offlane'] },
  { id: 104, name: 'Timbersaw', icon: '🪚', attr: 'str', roles: ['Offlane'] },
  { id: 105, name: 'Tinker', icon: '🔧', attr: 'int', roles: ['Mid'] },
  { id: 106, name: 'Tiny', icon: '🗻', attr: 'str', roles: ['Mid', 'Offlane', 'Carry'] },
  { id: 107, name: 'Treant Protector', icon: '🌳', attr: 'str', roles: ['Support', 'Offlane'] },
  { id: 108, name: 'Troll Warlord', icon: '🪓', attr: 'agi', roles: ['Carry'] },
  { id: 109, name: 'Tusk', icon: '🐘', attr: 'str', roles: ['Offlane', 'Support'] },
  { id: 110, name: 'Underlord', icon: '👹', attr: 'str', roles: ['Offlane'] },
  { id: 111, name: 'Undying', icon: '🧟', attr: 'str', roles: ['Offlane', 'Support'] },
  { id: 112, name: 'Ursa', icon: '🐻', attr: 'agi', roles: ['Carry'] },
  { id: 113, name: 'Vengeful Spirit', icon: '👻', attr: 'agi', roles: ['Support', 'Offlane'] },
  { id: 114, name: 'Venomancer', icon: '🐍', attr: 'agi', roles: ['Offlane', 'Support'] },
  { id: 115, name: 'Viper', icon: '🐍', attr: 'agi', roles: ['Mid', 'Offlane'] },
  { id: 116, name: 'Visage', icon: '🦅', attr: 'str', roles: ['Offlane', 'Mid'] },
  { id: 117, name: 'Void Spirit', icon: '🌀', attr: 'int', roles: ['Mid', 'Offlane'] },
  { id: 118, name: 'Warlock', icon: '📜', attr: 'int', roles: ['Support'] },
  { id: 119, name: 'Weaver', icon: '🪲', attr: 'agi', roles: ['Carry', 'Offlane'] },
  { id: 120, name: 'Windranger', icon: '🍃', attr: 'int', roles: ['Mid', 'Offlane', 'Support'] },
  { id: 121, name: 'Winter Wyvern', icon: '🐉', attr: 'int', roles: ['Support', 'Offlane'] },
  { id: 122, name: 'Witch Doctor', icon: '🪇', attr: 'int', roles: ['Support'] },
  { id: 123, name: 'Wraith King', icon: '👑', attr: 'str', roles: ['Carry', 'Offlane'] },
  { id: 124, name: 'Zeus', icon: '⚡', attr: 'int', roles: ['Mid'] },
];

export const BAN_PHASES = [
  { team: 'Radiant', ban: 1 }, { team: 'Dire', ban: 1 },
  { team: 'Radiant', ban: 2 }, { team: 'Dire', ban: 2 },
  { team: 'Radiant', ban: 3 }, { team: 'Dire', ban: 3 },
];

export const PICK_PHASES = [
  { team: 'Radiant', pick: 1 }, { team: 'Dire', pick: 1 },
  { team: 'Dire', pick: 2 }, { team: 'Radiant', pick: 2 },
  { team: 'Radiant', pick: 3 }, { team: 'Dire', pick: 3 },
  { team: 'Dire', pick: 4 }, { team: 'Radiant', pick: 4 },
  { team: 'Radiant', pick: 5 }, { team: 'Dire', pick: 5 },
];

export const BAN_PHASES_2 = [
  { team: 'Radiant', ban: 4 }, { team: 'Dire', ban: 4 },
  { team: 'Radiant', ban: 5 }, { team: 'Dire', ban: 5 },
  { team: 'Radiant', ban: 6 }, { team: 'Dire', ban: 6 },
  { team: 'Radiant', ban: 7 }, { team: 'Dire', ban: 7 },
];

export const ALL_PHASES = [
  ...BAN_PHASES.map((p, i) => ({ ...p, type: 'ban' as const, idx: i })),
  ...PICK_PHASES.map((p, i) => ({ ...p, type: 'pick' as const, idx: i })),
  ...BAN_PHASES_2.map((p, i) => ({ ...p, type: 'ban' as const, idx: i + 6 })),
];

const HERO_NAME_MAP: Record<string, string> = {
  "Anti-Mage": "antimage",
  "Centaur Warrunner": "centaur",
  "Clockwerk": "rattletrap",
  "Doom": "doom_bringer",
  "Io": "wisp",
  "Life Stealer": "life_stealer",
  "Magnus": "magnataur",
  "Nature's Prophet": "furion",
  "Necrophos": "necrolyte",
  "Outworld Destroyer": "obsidian_destroyer",
  "Queen of Pain": "queenofpain",
  "Shadow Fiend": "nevermore",
  "Timbersaw": "shredder",
  "Treant Protector": "treant",
  "Underlord": "abyssal_underlord",
  "Vengeful Spirit": "vengefulspirit",
  "Windranger": "windrunner",
  "Wraith King": "skeleton_king",
  "Zeus": "zuus",
};

export function getHeroImageUrl(hero: { name: string; id: number }): string {
  const key = HERO_NAME_MAP[hero.name] || hero.name.toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/ /g, '_');
  return `https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/icons/${key}.png`;
}
